[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_CHUTES_API_TOKEN = "your-token"
  NEXTAUTH_URL = "your-production-url"
  NEXTAUTH_SECRET = "your-secret"
  DATABASE_URL = "your-supabase-url"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = true 